### ISSUE TITLE
edge浏览器中首页渲染样式异常

### ISSUE THREAD

**Issue by langhaoabcd** [dotnet9/CodeWF#13]
![image](https://github.com/user-attachments/assets/491aa261-854e-4b32-b54d-e6f81a15133a)

**Comment by dotnet9** [comment]
非常感谢你提出的这个 Issue。我已经在 Google AdSense 后台对广告设置进行了调整，不过由于 Google AdSense 有其自身的学习机制，调整后的效果可能需要一些时间才会在网站首页显示出来。在此期间，还请你耐心等待一下，给它点时间来优化展示效果，再次感谢你的反馈！

Thank you very much for raising this Issue. I have already made adjustments to the ad settings in the Google AdSense backend. However, due to the self - learning mechanism of Google AdSense, it may take some time for the adjusted effect to be displayed on the home page of the website. During this period, please be patient and give it some time to optimize the display effect. Thank you again for your feedback!

**Comment by dotnet9** [comment]
感谢你反馈首页布局乱的问题。我已经在 Google AdSense 后台进行了调整，现在很高兴地告诉你，调整已经生效啦！你可以刷新页面看看，希望现在的首页布局能让你满意。再次感谢你的反馈，这对我们改进网站很有帮助。

Thank you for reporting the problem of the messy layout on the home page. I have made adjustments in the Google AdSense back - end, and I'm glad to tell you that the adjustments have already taken effect! You can refresh the page to have a look. I hope the current layout of the home page satisfies you. Thank you again for your feedback, which is very helpful for us to improve the website.
