### ISSUE TITLE
add data mapping function

### ISSUE THREAD

**Issue by cancanpapa** [dotnet9/CodeWF#20]
**### add data mapping function to  instanly retrieve mapped data.**

**For example:** 

"hello" in different languages
 French word  --english word --chinese word--japanese word--.........

**Method suggested**
GetMappedValue("Hello", "French")
GetMappedValue("Hello", "Chinese")
GetMappedValue("你好", "French")

**Note:**
Its not only intended for language mapping but also for any non-repeated/unique data in certain data group  which could be mapped to other relavant data from other data group.   

similar with bio-directional dictionary, but needs to have more cross directions.

**Comment by dotnet9** [comment]
Hi there,

Thanks for your suggestion. However, it seems you've raised this issue in the wrong repository. This functionality you're asking for has already been implemented in another project. 

In the code, we can conveniently obtain the translation string of the current language culture based on a strongly-typed Key. For example:

```csharp
var title = I18nManager.GetString(Localization.AskBotView.Title); // Get the current language
var titleZhCN = I18nManager.Instance.GetResource(Localization.Main.MainView.Title, "zh-CN"); // Get Simplified Chinese
var titleEnUS = I18nManager.Instance.GetResource(Localization.Main.MainView.Title, "en-US"); // Get English
```

Of course, specifying the language is also supported:

```xaml
<SelectableTextBlock u:FormItem.Label="Current Thread" Text="{markup:I18n {x:Static developModuleLanguage:Title2SlugView.Title}}" />
<SelectableTextBlock u:FormItem.Label="en-US" Text="{markup:I18n {x:Static developModuleLanguage:Title2SlugView.Title}, CultureName=en-US}" />
<SelectableTextBlock u:FormItem.Label="ja-JP" Text="{markup:I18n {x:Static developModuleLanguage:Title2SlugView.Title}, CultureName=ja-JP}" />
<SelectableTextBlock u:FormItem.Label="zh-CN" Text="{markup:I18n {x:Static developModuleLanguage:Title2SlugView.Title}, CultureName=zh-CN}" />
<SelectableTextBlock u:FormItem.Label="zh-Hant" Text="{markup:I18n {x:Static developModuleLanguage:Title2SlugView.Title}, CultureName=zh-Hant}" />
```

Since this isn't relevant to this particular project, I'm going to close this issue. If you have any other questions or need further assistance regarding the correct project, feel free to let us know.

Best regards,

[沙漠尽头的狼]
